main/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('auth/', include('authentication.urls')),
    path('store', include('shop.urls')),
    path('admin/', admin.site.urls),
]

shop/models.py
from _decimal import Decimal

from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.dispatch import receiver
from django.db import models, transaction
from django.db.models.signals import post_save, post_delete
from django.db.models import Sum


# Create your models here.
class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, verbose_name='product_name')
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Category')
    code = models.CharField(max_length=255, verbose_name='product_code')
    price = models.DecimalField(max_digits=20, decimal_places=2)
    unit = models.IntegerField(blank=True, null=True)
    image_url = models.URLField(blank=True, null=True)
    note = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'{self.name} - {self.price}'


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="Category")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat': self.pk})


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} - {self.amount}'

    @staticmethod
    def get_balance(user: User):
        amount = Payment.objects.filter(user=user,
                                        ).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class Order(models.Model):
    STATUS_CART = '1_card'
    STATUS_WAITING_FOR_PAYMENT = '2_waiting_for_payment'
    STATUS_PAID = '3_paid'
    STATUS_CHOICES = [
        (STATUS_PAID, 'cart'),
        (STATUS_WAITING_FOR_PAYMENT, 'waiting_for_payment'),
        (STATUS_PAID, 'paid')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=32, choices=STATUS_CHOICES, default=STATUS_CART)
    amount = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)

    first_name = models.CharField(blank=True, max_length=100, default='', null=False)
    last_name = models.CharField(blank=True, max_length=100, default='', null=False)
    email = models.EmailField(blank=True, default='', null=False)
    address = models.CharField(blank=True, max_length=255, default='', null=False)
    city = models.CharField(blank=True, max_length=100, default='', null=False)
    country = models.CharField(blank=True, max_length=100, default='', null=False)
    zip_code = models.CharField(blank=True, max_length=20, default='', null=False)
    tel = models.CharField(blank=True, max_length=20, default='', null=False)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.user} - {self.amount} - {self.status}'

    @staticmethod
    def get_cart(user: User):
        cart = Order.objects.filter(user=user,
                                    status=Order.STATUS_CART
                                    ).first()
        if cart and (timezone.now() - cart.creation_time).days > 7:
            cart.delete()
            cart = None
        if not cart:
            cart = Order.objects.create(user=user,
                                        status=Order.STATUS_CART,
                                        amount=0
                                        )
        return cart

    def get_amount(self):
        amount = Decimal(0)
        for item in self.orderitem_set.all():
            amount += item.amount
        return amount

    def make_order(self):
        items = self.orderitem_set.all()

        if items and self.status == Order.STATUS_CART:
            self.status = Order.STATUS_WAITING_FOR_PAYMENT
            self.save()
            auto_payment_unpaid_orders(self.user)

    @staticmethod
    def get_amount_of_unpaid_orders(user: User):
        amount = Order.objects.filter(user=user,
                                      status=Order.STATUS_WAITING_FOR_PAYMENT,
                                      ).aggregate(Sum('amount'))['amount__sum']
        return amount or Decimal(0)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)

    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=20, decimal_places=2, default=0)

    class Meta:
        ordering = ['pk']

    def __str__(self):
        return f'{self.product} - {self.price}'

    @property
    def amount(self):
        return self.quantity * (self.price - self.discount)


@transaction.atomic()
def auto_payment_unpaid_orders(user: User):
    unpaid_orders = Order.objects.filter(user=user,
                                         status=Order.STATUS_WAITING_FOR_PAYMENT)
    for order in unpaid_orders:
        if Payment.get_balance(user) < order.amount:
            break
        order.payment = Payment.objects.all().last()
        order.status = Order.STATUS_PAID
        order.save()
        Payment.objects.create(user=user,
                               amount=-order.amount)


@receiver(post_save, sender=OrderItem)
def recalculate_order_amount_after_save(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_delete, sender=OrderItem)
def recalculate_order_amount_after_delete(sender, instance, **kwargs):
    order = instance.order
    order.amount = order.get_amount()
    order.save()


@receiver(post_save, sender=Payment)
def auto_payment(sender, instance, **kwargs):
    user = instance.user
    auto_payment_unpaid_orders(user)

templates/store/cart.html
{% extends 'templates/basepage.html' %}
{% load static %}
{% block content %}

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <h3 class="breadcrumb-header">Checkout</h3>
                <ul class="breadcrumb-tree">
                    <li><a href="#">Home</a></li>
                    <li class="active">Checkout</li>
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->

<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <div class="col-md-7">
                <form method="post" action="{% url 'make_order' %}">
                    {% csrf_token %}
                    <!-- Billing Details -->
                    <div class="billing-details">
                        <div class="section-title">
                            <h3 class="title">Billing address</h3>
                        </div>


                        <div class="form-group">
                            <input class="input" type="text" name="first_name" placeholder="First Name" value="{{ form.first_name.value }}">
                            {% if form.first_name.errors %}
                                <span style="color:red;">{{ form.first_name.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input class="input" type="text" name="last_name" placeholder="Last Name" value="{{ form.last_name.value }}">
                            {% if form.last_name.errors %}
                                <span style="color:red;">{{ form.last_name.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input class="input" type="email" name="email" placeholder="Email" value="{{ form.email.value }}">
                            {% if form.email.errors %}
                                <span style="color:red;">{{ form.email.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input class="input" type="text" name="address" placeholder="Address" value="{{ form.address.value }}">
                            {% if form.address.errors %}
                                <span style="color:red;">{{ form.address.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input class="input" type="text" name="city" placeholder="City" value="{{ form.city.value }}">
                            {% if form.city.errors %}
                                <span style="color:red;">{{ form.city.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input class="input" type="text" name="country" placeholder="Country" value="{{ form.country.value }}">
                            {% if form.country.errors %}
                                <span style="color:red;">{{ form.country.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input class="input" type="text" name="zip_code" placeholder="ZIP Code" value="{{ form.zip_code.value }}">
                            {% if form.zip_code.errors %}
                                <span style="color:red;">{{ form.zip_code.errors }}</span>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <input class="input" type="tel" name="tel" placeholder="Telephone" value="{{ form.tel.value }}">
                            {% if form.tel.errors %}
                                <span style="color:red;">{{ form.tel.errors }}</span>
                            {% endif %}
                        </div>
                    </div>


                    <!-- /Shiping Details -->

                    <!-- Order notes -->
                    <div class="order-notes">
                        <textarea class="input" placeholder="Order Notes"></textarea>
                    </div>
                    <!-- /Order notes -->
                    <button type="submit" class="primary-btn order-submit">Place order</button>
                </form>
            </div>


            <!-- Order Details -->
            <div class="col-md-5 order-details">
                <div class="section-title text-center">
                    <h3 class="title">Your Order</h3>
                </div>
                <div class="order-summary">
                    <div class="order-col">
                        <div><strong>PRODUCT</strong></div>
                        <div><strong>TOTAL</strong></div>
                    </div>
                    <div class="order-products">
                        {% for item in items %}
                        <div class="order-col">
                            <form method="post" action="{% url 'cart_delete_item' pk=item.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="delete"
                                        style="top: 0;
											left: 10;
											height: 20px;
											width: 20px;
											text-align: center;
											font-size: 12px;
											padding: 0;
											background: #FFF;
											border: none;
											color: #1e1f29;">
                                    <i class="fa fa-close"></i></button>
                            </form>
                            <div>{{ item.quantity }}x {{ item.product }}</div>
                            <div>${{ item.price }}</div>

                        </div>
                        {% endfor %}
                    </div>
                    <div class="order-col">
                        <div>Shiping</div>
                        <div><strong>FREE</strong></div>
                    </div>
                    <div class="order-col">
                        <div><strong>TOTAL</strong></div>
                        <div><strong class="order-total">${{ cart.amount }}</strong></div>
                    </div>
                </div>
                <div class="payment-method">
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-1">
                        <label for="payment-1">
                            <span></span>
                            Direct Bank Transfer
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut
                                labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-2">
                        <label for="payment-2">
                            <span></span>
                            Cheque Payment
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut
                                labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-3">
                        <label for="payment-3">
                            <span></span>
                            Paypal System
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut
                                labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                </div>
                <div class="input-checkbox">
                    <input type="checkbox" id="terms">
                    <label for="terms">
                        <span></span>
                        I've read and accept the <a href="#">terms & conditions</a>
                    </label>
                </div>


            </div>
            <!-- /Order Details -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>


<!-- /SECTION -->

<!-- NEWSLETTER -->
<div id="newsletter" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <div class="newsletter">
                    <p>Sign Up for the <strong>NEWSLETTER</strong></p>
                    <form>
                        <input class="input" type="email" placeholder="Enter Your Email">
                        <button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
                    </form>
                    <ul class="newsletter-follow">
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /NEWSLETTER -->
{% endblock %}

templates/store/list_categories.html
{% load nav_tags %}
{% if cat_selected == 0 %}
<li class="input-checkbox">All</li>
{% else %}
<li><a href="{% url 'store' %}">All</a></li>
{% endif %}
{% for c in cats %}
    {% if c.pk == cat_selected %}
        <li class="input-checkbox">{{ c.name }}<small> ({{ c.product_count }})</small></li>

    {% else %}
        <li><a href="{% url 'category' cat_id=c.pk %}">{{ c.name }} <small> ({{ c.product_count }})</small></a></li>
    {% endif %}
{% endfor %}

templates/store/payment.html
{% extends 'templates/basepage.html' %}
{% load static %}
{% load info_tags %}
{% block content %}
<h3>Your current balance: {% balance_context request %} USD</h3>
<form method="post" action="{% url 'make_payment' %}">
    {% csrf_token %}
    <div class="form-group">
        <input class="input" type="number" name="amount" placeholder="Amount">
        {% if form.amount.errors %}
        <span style="color:red;">{{ form.amount.errors }}</span>
        {% endif %}
        <button type="submit">Top up</button>
    </div>
</form>

{% endblock %}

templates/store/store.html
{% extends 'templates/basepage.html' %}
{% load static %}
{% load nav_tags %}
{% block content %}

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- ASIDE -->
					<div id="aside" class="col-md-3">
						                    <!-- aside Widget -->
                    <div class="aside">
                        <h3 class="aside-title"></h3>
                        <div class="checkbox-filter">
                            {% show_categories cat_selected=cat_selected %}
                        </div>
                    </div>
                    <!-- /aside Widget -->

						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Price</h3>
							<div class="price-filter">
								<div id="price-slider"></div>
								<div class="input-number price-min">
									<input id="price-min" type="number">
									<span class="qty-up">+</span>
									<span class="qty-down">-</span>
								</div>
								<span>-</span>
								<div class="input-number price-max">
									<input id="price-max" type="number">
									<span class="qty-up">+</span>
									<span class="qty-down">-</span>
								</div>
							</div>
						</div>
						<!-- /aside Widget -->

						<!-- aside Widget -->
						<div class="aside">
<!--							<h3 class="aside-title">Brand</h3>-->
<!--							<div class="checkbox-filter">-->
<!--								<div class="input-checkbox">-->
<!--									<input type="checkbox" id="brand-1">-->
<!--									<label for="brand-1">-->
<!--										<span></span>-->

<!--										<small>(578)</small>-->
<!--									</label>-->
<!--								</div>-->
<!--								<div class="input-checkbox">-->
<!--									<input type="checkbox" id="brand-2">-->
<!--									<label for="brand-2">-->
<!--										<span></span>-->

						</div>

					</div>
					<!-- /ASIDE -->

					<!-- STORE -->
					<div id="store" class="col-md-9">
						<!-- store top filter -->
						<div class="store-filter clearfix">
							<div class="store-sort">
								<label>
									Sort By:
									<select class="input-select">
										<option value="0">Popular</option>
										<option value="1">Position</option>
									</select>
								</label>

								<label>
									Show:
									<select class="input-select">
										<option value="0">20</option>
										<option value="1">50</option>
									</select>
								</label>
							</div>
							<ul class="store-grid">
								<li class="active"><i class="fa fa-th"></i></li>
								<li><a href="#"><i class="fa fa-th-list"></i></a></li>
							</ul>
						</div>
						<!-- /store top filter -->

						<!-- store products -->
						<div class="row">
								<!-- product -->
								{% for product in object_list %}
									<div class="col-md-4 col-xs-6">
										<form method="post" action="{% url 'add_item_to_cart' product.pk %}">

											<div class="product">
												<div class="product-img">
													<img src="{{product.image_url}}" alt="">
													<div class="product-label">
													</div>
												</div>
												<div class="product-body">
													<p class="product-category">{{ product.cat }}</p>
													<h3 class="product-name"><a href="{% url 'product' product.pk %}">{{ product.name }}</a></h3>
													<h4 class="product-price">${{ product.price }}</h4>
													<div class="product-rating">
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
													</div>
													<div class="product-btns">
														<button class="quick-view"><i class="fa fa-eye"></i>
															<a class="tooltipp" href="{% url 'product' product.pk %}">quick view</a>
															</button>
													</div>
												</div>
												<div class="add-to-cart">
													{% csrf_token %}

													<label class="form-label" for="id_quantity">Quantity:</label>
													{% if quantity_form.errors %}
													    <p class="error-message">{{ quantity_form.errors.quantity }}</p>
													{% else %}
														<input type="number" name="quantity" value="1" min="1" max="{{ product.unit }}"
															   required id="id_quantity"/>
													{% endif %}
													<button class="add-to-cart-btn" type="submit"> add to cart</button>
												</div>
											</div>
										</form>
									</div>
							{% endfor %}

						</div>
						<!-- /store products -->

						<!-- store bottom filter -->
						{% with product_count=object_list|length %}
							<div class="store-filter clearfix">
								<span class="store-qty">Showing {{ product_count }} product{% if product_count != 1 %}s{% endif %}</span>
								<ul class="store-pagination">
								</ul>
							</div>
						{% endwith %}
						<!-- /store bottom filter -->
					</div>
					<!-- /STORE -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Sign Up for the <strong>NEWSLETTER</strong></p>
							<form>
								<input class="input" type="email" placeholder="Enter Your Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->
{% endblock %}